# Copyright (C) 2024 bytesatwork AG - https://www.bytesatwork.io

VERSION="1"
CUSTOMER_NAME="bytesatwork"
BUILD_NAME="bytesatwork-bytedevkit-imx93"

YOCTO_MACHINES="bytedevkit-imx93"
YOCTO_DISTRO="poky-bytesatwork"
YOCTO_IMAGES="bytesatwork-minimal-image"

SDK_MACHINES="${YOCTO_MACHINES}"
SDK_IMAGE="bytesatwork-minimal-image"

CONFIG_DOCKER="debian-12"

REPO_URL="git@github.com:bytesatwork/bsp-platform-nxp.git"

export_artifacts() {
	docker cp -L "$id:/home/yocto/yocto/build/tmp/deploy/images/bytedevkit-imx93/bytesatwork-minimal-image-bytedevkit-imx93.rootfs.manifest" .
	docker cp -L "$id:/home/yocto/yocto/build/tmp/deploy/images/bytedevkit-imx93/bytesatwork-minimal-image-bytedevkit-imx93.rootfs.spdx.tar.zst" .
	docker cp -L "$id:/home/yocto/yocto/build/tmp/deploy/images/bytedevkit-imx93/bytesatwork-minimal-image-bytedevkit-imx93.rootfs.wic.bmap" .
	docker cp -L "$id:/home/yocto/yocto/build/tmp/deploy/images/bytedevkit-imx93/bytesatwork-minimal-image-bytedevkit-imx93.rootfs.wic.gz" .
	docker cp -L "$id:/home/yocto/yocto/build/tmp/deploy/images/bytedevkit-imx93/imx-boot-bytedevkit-imx93-sd.bin-flash_singleboot" .
}

export_artifacts_sdk() {
	docker cp -L "$id:/home/yocto/yocto/build/tmp/deploy/sdk/poky-bytesatwork-glibc-x86_64-bytesatwork-minimal-image-cortexa55-bytedevkit-imx93-toolchain-5.0.5-host.spdx.tar.zst" .
	docker cp -L "$id:/home/yocto/yocto/build/tmp/deploy/sdk/poky-bytesatwork-glibc-x86_64-bytesatwork-minimal-image-cortexa55-bytedevkit-imx93-toolchain-5.0.5-target.spdx.tar.zst" .
	docker cp -L "$id:/home/yocto/yocto/build/tmp/deploy/sdk/poky-bytesatwork-glibc-x86_64-bytesatwork-minimal-image-cortexa55-bytedevkit-imx93-toolchain-5.0.5.host.manifest" .
	docker cp -L "$id:/home/yocto/yocto/build/tmp/deploy/sdk/poky-bytesatwork-glibc-x86_64-bytesatwork-minimal-image-cortexa55-bytedevkit-imx93-toolchain-5.0.5.sh" .
	docker cp -L "$id:/home/yocto/yocto/build/tmp/deploy/sdk/poky-bytesatwork-glibc-x86_64-bytesatwork-minimal-image-cortexa55-bytedevkit-imx93-toolchain-5.0.5.target.manifest" .
}
