# Copyright (C) 2023 bytes at work AG - https://www.bytesatwork.io

VERSION="1"
CUSTOMER_NAME="bytesatwork"
BUILD_NAME="bytesatwork-bytedevkit-imx8mp"

YOCTO_MACHINES="bytedevkit-imx8mp"
YOCTO_DISTRO="poky-bytesatwork"
YOCTO_IMAGES="bytesatwork-minimal-image"

SDK_MACHINES="${YOCTO_MACHINES}"
SDK_IMAGE="bytesatwork-minimal-image"

CONFIG_DOCKER="debian-12"

REPO_URL="git@github.com:bytesatwork/bsp-platform-nxp.git"

export_artifacts() {
	docker cp -L "$id:/home/yocto/yocto/build/tmp/deploy/images/bytedevkit-imx8mp/imx-boot-bytedevkit-imx8mp-sd.bin-flash_evk" .
	docker cp -L "$id:/home/yocto/yocto/build/tmp/deploy/images/bytedevkit-imx8mp/bytesatwork-minimal-image-bytedevkit-imx8mp.manifest" .
	docker cp -L "$id:/home/yocto/yocto/build/tmp/deploy/images/bytedevkit-imx8mp/bytesatwork-minimal-image-bytedevkit-imx8mp.wic.bmap" .
	docker cp -L "$id:/home/yocto/yocto/build/tmp/deploy/images/bytedevkit-imx8mp/bytesatwork-minimal-image-bytedevkit-imx8mp.wic.gz" .
}

export_artifacts_sdk() {
	docker cp -L "$id:/home/yocto/yocto/build/tmp/deploy/sdk/poky-bytesatwork-glibc-x86_64-bytesatwork-minimal-image-cortexa53-crypto-bytedevkit-imx8mp-toolchain-4.0.18.host.manifest" .
	docker cp -L "$id:/home/yocto/yocto/build/tmp/deploy/sdk/poky-bytesatwork-glibc-x86_64-bytesatwork-minimal-image-cortexa53-crypto-bytedevkit-imx8mp-toolchain-4.0.18.sh" .
	docker cp -L "$id:/home/yocto/yocto/build/tmp/deploy/sdk/poky-bytesatwork-glibc-x86_64-bytesatwork-minimal-image-cortexa53-crypto-bytedevkit-imx8mp-toolchain-4.0.18.target.manifest" .
}
